name: faltool
description: A new Flutter package project.
version: 1.0.13
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #PLATFORM: All
  package_info_plus: ^8.1.3
  device_info_plus: ^11.2.1
  share_plus: ^10.1.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  ansicolor: ^2.0.3
  uuid: ^4.5.1
  logger: ^2.5.0
  stack_trace: ^1.11.0
  dartx: ^1.2.0
  rxdart: ^0.28.0
  enum_to_string: ^2.0.1
  dartz: ^0.10.1
  version: ^3.0.2
  crypto: ^3.0.6
  url_strategy: ^0.3.0
  timeago: ^3.7.0
  numeral: ^3.0.0
  money_formatter: ^0.0.6
  shared_preferences: ^2.3.5

  #PLATFORM: Android, iOS, Linux, MacOS, Windows
  path_provider: ^2.1.5
  universal_io: ^2.2.2

  #PLATFORM: Android, iOS, MacOS, Web
#  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.8.0

flutter:
