name: falconnect
description: A new Flutter package project.
version: 1.3.4
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  faltool:
    path: ../faltool
  falmodel:
    path: ../falmodel

  #PLATFORM: All
  ansicolor: ^2.0.3
  dio: ^5.7.0
  retrofit: ^4.4.2
  web_socket_channel: ^3.0.1
  connectivity_plus: ^6.1.2
  dio_cache_interceptor: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
