name: falkit
description: A new Flutter package project.
version: 1.1.7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  faltool:
    path: ../faltool

  #PLATFORM: All
  gap: ^3.0.1
  flutter_svg: ^2.0.16
  extended_image: ^9.0.7
  smooth_page_indicator: ^1.2.0+3
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
