name: falstore
description: A new Flutter package project.
version: 1.1.10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  faltool:
    path: ../faltool


  #PLATFORM: All
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
